name          'chartbeat/mdadm'
version       '0.0.1'
source        'https://github.com/chartbeat-labs/puppet-mdadm'
author        'chartbeat'
license       'MIT'
summary       'Module to manage mdadm'
description   'Mdadm module for Puppet'
project_page  'https://github.com/chartbeat-labs/puppet-mdadm'

dependency 'puppetlabs/stdlib', '>= 3.0.0'
