# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----

# ---- original file header ----
#
# @summary
#       Check that devices exist and are block devices.
#
#    Example: check_devices(['/dev/sdb', '/dev/sdc'], $::blockdevices)
#
Puppet::Functions.create_function(:'mdadm::check_devices') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    

    raise(Puppet::ParseError, "check_devices(): Wrong number of arguments " +
      "given (#{args.size} for 2)") if args.size != 2

    # Strip /dev/ from devices
    devices = args[0].map { |d| d.split('/')[2] }

    # Fact comes as a comma separated string
    blockdevs = args[1].split(',')

    [devices, blockdevs].each do |device|
      unless [Array].include?(device.class)
        raise(Puppet::ParseError, "check_devices(): Requires and Array (given (#{device.class}))")
      end
    end

    return (devices - blockdevs).empty?
  
  end
end
